# Generated by Django 5.1.7 on 2025-03-30 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_id', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MoyskladProduct',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('article', models.CharField(blank=True, max_length=100)),
                ('vat', models.IntegerField(default=0)),
                ('vat_enabled', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('barcodes', models.JSONField(default=list)),
                ('payment_item_type', models.CharField(max_length=50)),
                ('meta', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='moysklad_mo_name_cc5561_idx'), models.Index(fields=['article'], name='moysklad_mo_article_18c6de_idx'), models.Index(fields=['code'], name='moysklad_mo_code_76f482_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moysklad.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='moysklad.moyskladproduct')),
            ],
        ),
    ]
