# Generated by Django 5.1.7 on 2025-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladproduct',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/medium/'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/original/'),
        ),
    ]
