# Generated by Django 5.1.7 on 2025-03-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price2_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='moysklad.currency'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price2_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price2_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='moysklad.currency'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='price_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
