# Generated by Django 5.1.7 on 2025-03-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0002_remove_moyskladproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladproduct',
            name='price2_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
