# Generated by Django 5.1.7 on 2025-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0004_alter_moyskladproduct_options_moyskladproduct_aka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moyskladproduct',
            options={'ordering': ['name'], 'verbose_name': 'Товар МойСклад', 'verbose_name_plural': 'Товары МойСклад'},
        ),
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='price2_currency',
        ),
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='price2_type',
        ),
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='price2_value',
        ),
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='buy_price_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='effective_vat',
            field=models.IntegerField(default=0, verbose_name='Эффективный НДС'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='effective_vat_enabled',
            field=models.BooleanField(default=False, verbose_name='Эффективный НДС включен'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='external_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внешний код'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='images',
            field=models.JSONField(default=list, verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='min_price_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='minimum_balance',
            field=models.FloatField(default=0.0, verbose_name='Минимальный остаток'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='product_folder_description',
            field=models.TextField(blank=True, verbose_name='Описание группы'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='product_folder_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='supplier_actual_address',
            field=models.TextField(blank=True, verbose_name='Фактический адрес поставщика'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='supplier_legal_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юр. название поставщика'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон поставщика'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='payment_item_type',
            field=models.CharField(default='GOOD', max_length=50, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='moyskladproduct',
            index=models.Index(fields=['price_value'], name='moysklad_mo_price_v_37bc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='moyskladproduct',
            index=models.Index(fields=['archived'], name='moysklad_mo_archive_009815_idx'),
        ),
    ]
