# Generated by Django 5.1.7 on 2025-04-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0005_alter_moyskladproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='meta',
        ),
    ]
