# Generated by Django 5.1.7 on 2025-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0006_remove_moyskladproduct_meta'),
    ]

    operations = [
    ]
