# Generated by Django 5.1.7 on 2025-04-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0007_remove_meta_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladproduct',
            name='barcodes',
            field=models.JSONField(blank=True, default=list, verbose_name='Штрихкоды'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='buy_price_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='effective_vat',
            field=models.IntegerField(blank=True, default=0, verbose_name='Эффективный НДС'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='min_price_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='minimum_balance',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='product_folder_name',
            field=models.CharField(blank=True, default='Основная', max_length=255, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='volume',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='moyskladproduct',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Вес'),
        ),
    ]
