# Generated by Django 5.1.7 on 2025-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0008_alter_moyskladproduct_barcodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladproduct',
            name='moysklad_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на товар в интерфейсе МойСклад', max_length=500, verbose_name='Ссылка в МойСклад'),
        ),
    ]
