# Generated by Django 5.1.7 on 2025-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moysklad', '0009_moyskladproduct_moysklad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladproduct',
            name='supplier_legal_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поставщик'),
        ),
    ]
