# Generated by Django 5.1.7 on 2025-04-24 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Телефон должен содержать только цифры.')], verbose_name='Телефон'),
        ),
    ]
