# Generated by Django 5.1.7 on 2025-04-24 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_buyer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Product',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Телефон должен содержать только цифры. Формат ввода 87776665544')], verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
