# Generated by Django 5.1.7 on 2025-04-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moysklad", "0008_alter_moyskladproduct_barcodes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductForSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "aka",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена продажи"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активен для продажи"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="Рейтинг")),
                (
                    "moysklad_product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="for_sale",
                        to="moysklad.moyskladproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар для продажи",
                "verbose_name_plural": "Товары для продажи",
                "ordering": ["name"],
            },
        ),
    ]
