# Generated by Django 5.1.7 on 2025-04-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforsale',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент наценки'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='sale_price_moy_sklad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Цена продажи мойсклад'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='supplier_legal_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='productforsale',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Цена продажи'),
        ),
    ]
