# Generated by Django 5.1.7 on 2025-04-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productforsale_country_productforsale_group_and_more'),
        ('moysklad', '0009_moyskladproduct_moysklad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforsale',
            name='moysklad_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_sale', to='moysklad.moyskladproduct', verbose_name='Продукт из МойСклад'),
        ),
    ]
