# Generated by Django 5.1.7 on 2025-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productforsale_moysklad_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforsale',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Цена продажи'),
        ),
    ]
