# Generated by Django 5.1.7 on 2025-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_info',
            field=models.TextField(blank=True, verbose_name='Допольнительная информация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен'), ('Другое', 'Другое')], default='Обрабатывается', max_length=255, verbose_name='Статус'),
        ),
    ]
