# Generated by Django 5.1.7 on 2025-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_other_info_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='other_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
