# Generated by Django 5.1.7 on 2025-05-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обрабатывается', 'Обрабатывается'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен'), ('Другое', 'Другое')], default='Обрабатывается', max_length=255, verbose_name='Статус'),
        ),
    ]
